// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn-XtDLw7xoHIglXocFx3oVxw4corV1e8',
    appId: '1:441058980658:web:8100947abeede21fad9d2b',
    messagingSenderId: '441058980658',
    projectId: 'mo-score',
    authDomain: 'mo-score.firebaseapp.com',
    storageBucket: 'mo-score.appspot.com',
    measurementId: 'G-55936WCMQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1l_umJbcqc3jghVFyWoFrZn9IiE13P0I',
    appId: '1:441058980658:android:766966d0faabe01dad9d2b',
    messagingSenderId: '441058980658',
    projectId: 'mo-score',
    storageBucket: 'mo-score.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3TmHYcNbT74dF_Ww_2fmHklr2nQbhl-Y',
    appId: '1:441058980658:ios:53379c76e09cd55bad9d2b',
    messagingSenderId: '441058980658',
    projectId: 'mo-score',
    storageBucket: 'mo-score.appspot.com',
    iosClientId: '441058980658-b8dtlagotjc7ia8279dainvkctdf6aip.apps.googleusercontent.com',
    iosBundleId: 'com.impactsolutions.moscore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3TmHYcNbT74dF_Ww_2fmHklr2nQbhl-Y',
    appId: '1:441058980658:ios:53379c76e09cd55bad9d2b',
    messagingSenderId: '441058980658',
    projectId: 'mo-score',
    storageBucket: 'mo-score.appspot.com',
    iosClientId: '441058980658-b8dtlagotjc7ia8279dainvkctdf6aip.apps.googleusercontent.com',
    iosBundleId: 'com.impactsolutions.moscore',
  );
}
